FROM registry.redhat.io/rhel10/rhel-bootc:latest@sha256:fed7afc7a86a5414b9e74003dda90be5df044e4d29060dfb1a79413037fdb67d

COPY ./bootc/rhel10/etc /etc/
RUN systemctl disable kdump
RUN dnf -y install rhc dnf-plugins-core vim zsh tmux tuned
RUN dnf clean all
