FROM registry.redhat.io/rhel10/rhel-bootc:latest@sha256:c9503b9375dd19446bfc71aa0b238e29fa723dd0b02d7dd25cc63166d83e335f

COPY ./bootc/rhel10/etc /etc/
COPY ./bootc/rhel10/usr /usr/
RUN <<EOF
  systemctl disable kdump
  systemctl mask rpm-ostree-countme.time
  dnf install -y rhc dnf-plugins-core vim zsh tmux systemd-resolved tuned
  dnf clean all
  systemctl enable systemd-resolved.service
  echo 'L /etc/resolv.conf - - - - /run/systemd/resolve/stub-resolv.conf' > /usr/lib/tmpfiles.d/resolv-conf.conf
EOF
