FROM registry.redhat.io/rhel10/rhel-bootc:latest@sha256:21ad1011c99bf601d931d043e25541da72c2fe14de33c78f62d4a483ed425c9a

COPY ./bootc/rhel10/etc /etc/
COPY ./bootc/rhel10/usr /usr/
RUN <<EOF
  systemctl disable kdump
  systemctl mask rpm-ostree-countme.time
  dnf install -y rhc dnf-plugins-core vim zsh tmux systemd-resolved tuned
  dnf clean all
  systemctl enable systemd-resolved.service
EOF
