ARG K3S_VERSION=v1.34.1+k3s1
ARG K3S_AGENT=false

COPY ./bootc/common/k3s/etc /etc/
COPY ./bootc/common/k3s/usr /usr/
COPY ./bootc/common/k3s/var /var/

# CNI plugins expect to write to /opt/cni/bin, so we need to make that writeable
# RUN systemctl enable ostree-state-overlay@opt.service
RUN <<EOF
  mkdir /var/opt/cni
  ln -sr /var/opt/cni /opt/cni
EOF

RUN <<EOF
  set -x
  if [ $(uname -m) = 'aarch64' ]; then
    SUFFIX='-arm64'
  fi
  curl -sfL https://github.com/k3s-io/k3s/releases/download/${K3S_VERSION}/k3s${SUFFIX:-''} \
  -o /usr/local/bin/k3s
  chmod +x /usr/local/bin/k3s
  ln -s /usr/local/bin/k3s /usr/local/bin/crictl
  ln -s /usr/local/bin/k3s /usr/local/bin/ctr
  ln -s /usr/local/bin/k3s /usr/local/bin/kubectl
  dnf -y install k3s-selinux iscsi-initiator-utils nfs-utils
  dnf clean all
  systemctl enable iscsid.service
  systemctl enable k3s.service
EOF

RUN <<EOF
  set -x
  if [ ${K3S_AGENT} = 'true' ]; then
    sed -i '/^ExecStart/s/server/agent/' /etc/systemd/system/k3s.service
    rm /etc/systemd/system/k3s-cleanup-shutdown-pods.service
  else
    systemctl enable k3s-cleanup-shutdown-pods.service
  fi
EOF
