COPY ./bootc/common/clevis/usr /usr/

RUN <<EOF
  set -x
  dnf -y install clevis-systemd clevis-dracut
  dnf clean all
  kver=$(cd /usr/lib/modules && echo *)
  rm /usr/lib/modules/$kver/initramfs.img
  dracut -vf /usr/lib/modules/$kver/initramfs.img $kver
EOF
