FROM quay.io/fedora/fedora-bootc:latest@sha256:f804bd7a5c680b65e77ce7272cf0f04ca77e049f836df4e9added920fc733fcc

COPY ./bootc/fedora/etc /etc/
RUN <<EOF
   dnf -y install dnf5-plugins vim tmux tuned
   dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
   dnf install -y tailscale
   dnf clean all
   systemctl enable tailscaled
EOF
