FROM quay.io/fedora/fedora-bootc:latest@sha256:4f826a95586ae24a4a8c7ab2bb34c8bb045dcb04d26fbff71d9da57a3c4fe25e

COPY ./bootc/fedora/etc /etc/
RUN <<EOF
  systemctl mask rpm-ostree-countme.time
  update-ca-trust
  dnf -y install dnf5-plugins vim tmux tuned
  dnf clean all
  echo 'L /etc/resolv.conf - - - - /run/systemd/resolve/stub-resolv.conf' > /usr/lib/tmpfiles.d/resolv-conf.conf
EOF
