FROM quay.io/fedora/fedora-bootc:latest@sha256:3a163c8ecd865539769d6c784a9dc482350a2397f47a26bab5f2cedbc4afb0b4

COPY ./bootc/fedora/etc /etc/
RUN <<EOF
   dnf -y install dnf5-plugins vim tmux tuned
   dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo
   dnf install -y tailscale
   dnf clean all
   systemctl enable tailscaled
EOF
