FROM registry.redhat.io/rhel9/rhel-bootc:latest@sha256:faa2f528f00f0b41550f4ee6c069c5d3202382e93bb12e8f306e9e1cd5ee8675

COPY ./bootc/rhel9/etc /etc/
RUN systemctl disable kdump
RUN dnf -y install rhc dnf-plugins-core vim zsh tmux systemd-resolved tuned
RUN dnf clean all
RUN systemctl enable systemd-resolved.service
