FROM registry.redhat.io/rhel9/rhel-bootc:latest@sha256:f2ceda4e98def81f5e4c8911678a72b3e90f82e6272b63fed5596816b9e64f60

COPY ./bootc/rhel9/etc /etc/
RUN <<EOF
  systemctl disable kdump
  systemctl mask rpm-ostree-countme.timer
  dnf install -y rhc dnf-plugins-core vim zsh tmux systemd-resolved tuned
  dnf clean all
  systemctl enable systemd-resolved.service
  echo 'L /etc/resolv.conf - - - - /run/systemd/resolve/stub-resolv.conf' > /usr/lib/tmpfiles.d/resolv-conf.conf
EOF
