FROM registry.redhat.io/rhel9/rhel-bootc:latest@sha256:0ba8c0502c98ec0660d0f4d5ddf090c53a4ab40e4129b9669a80051d8240122a

COPY ./bootc/rhel9/etc /etc/
RUN <<EOF
  systemctl disable kdump
  dnf install -y rhc dnf-plugins-core vim zsh tmux systemd-resolved tuned
  dnf clean all
  systemctl enable systemd-resolved.service
EOF
