ENV K3S_VERSION=v1.34.1+k3s1

COPY ./bootc/fedora/k3s/etc /etc/
COPY ./bootc/fedora/k3s/usr /usr/

# CNI plugins expect to write to /opt/cni/bin, so we need to make that writeable
RUN systemctl enable ostree-state-overlay@opt.service

RUN <<EOF
  set -x
  if [ $(uname -m) = 'aarch64' ]; then
    SUFFIX='-arm64'
  fi
  curl -sfL https://github.com/k3s-io/k3s/releases/download/${K3S_VERSION}/k3s${SUFFIX:-''} \
  -o /usr/local/bin/k3s
  chmod +x /usr/local/bin/k3s
  ln -s /usr/local/bin/k3s /usr/local/bin/crictl
  ln -s /usr/local/bin/k3s /usr/local/bin/ctr
  ln -s /usr/local/bin/k3s /usr/local/bin/kubectl
  dnf -y install k3s-selinux iscsi-initiator-utils nfs-utils
  dnf clean all
  systemctl enable iscsid.service
  systemctl enable k3s.service
EOF
