name: Build RHEL9 bootc-k3s-agent image
on:
  workflow_dispatch:
  push:
    paths:
      - bootc/rhel9/Containerfile
      - bootc/rhel9/tailscale/**
      - bootc/common/kubevirt/**
      - bootc/common/k3s/**
    branches:
      - main

jobs:
  build_bootc:
    uses: ./.github/workflows/build-rhel-bootc.yml
    with:
      image_name: rhel9/rhel-bootc-k3s-agent
      build-args: |
        K3S_AGENT=true
        LONGHORN=true
      containerfiles: |
        bootc/rhel9/Containerfile
        bootc/rhel9/tailscale/Containerfile
        bootc/common/kubevirt/Containerfile
        bootc/common/k3s/Containerfile
    permissions:
      contents: read
      packages: write
    secrets: inherit
