name: Build RHEL10 image
on:
  workflow_dispatch:
  push:
    paths:
      - bootc/rhel10/Containerfile
      - bootc/rhel10/etc/**
    branches:
      - main

jobs:
  build_bootc:
    uses: ./.github/workflows/build-rhel-bootc.yml
    with:
      image_name: rhel10/rhel-bootc
      containerfiles: |
        bootc/rhel10/Containerfile
    permissions:
      contents: read
      packages: write
    secrets: inherit
